### ISSUE TITLE
Public component "All FOMs" causes javascript console error

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#99]
Navigate to public component
Open javascript console
Click "All FOMs" link (top right).
Get the following javascript error:
ERROR TypeError: Cannot read properties of null (reading 'addLayer')
    at o.mapLayersUpdate (main.7047c0990f3632297813.js:1:2457457)
    at m.updateOnLayersChange (main.7047c0990f3632297813.js:1:835572)

Note that the user experience does NOT seem to be impacted, so priority is low.

Was able to reproduce this in current production, so this is a pre-existing defect, not introduced by the latest changes.

**Comment by gormless87** [comment]
This may have been addressed, testing required.

**Comment by basilv** [comment]
I'm unable to reproduce in FOM Test, I'm pretty confident this has been addressed so closing.

**Comment by basilv** [comment]
Ignore my comment (I deleted it :), I was able to reproduce after properly reading my original description above. This is very low priority...

**Comment by basilv** [comment]
Can also be reproduced by navigating to FOM Public (e.g. from browser bookmark), then hiding splash screen and clicking top left 'home page' link to get splash screen to reappear.
